spring:
  application:
    name: discodeit

  profiles:
    active: dev

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

  api-docs:
    path: /my-api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.2-M8
    java-version: 17
    spring-boot-version: 3.5.14

  config:
    datasource:
      url: ${spring.datasource.url}

    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
      open-in-view: ${spring.jpa.open-in-view:true}

    storage:
      type: ${discodeit.storage.type}

    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size:10MB}
      max-request-size: ${spring.servlet.multipart.max-request-size:10MB}

discodeit:
  jwt:
    issuer: discodeit
    access-token-expiration: 30m
    refresh-token-expiration: 14d