spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: ${PORT:8080}

logging:
  level:
    com.sprint.mission.discodeit: info

discodeit:
  admin:
    username: ${ADMIN_USERNAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}

  storage:
    type: s3

    s3:
      region: ${AWS_S3_REGION:ap-northeast-2}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}